
export const SCHEMA_LOAD_INITIATE = "SCHEMA_LOAD_INITIATE"
export const SCHEMA_LOAD_START = "SCHEMA_LOAD_START"
export const SCHEMA_LOAD_FINISHED = "SCHEMA_LOAD_FINISHED"
export const SCHEMA_LOAD_FAILED = "SCHEMA_LOAD_FAILED"

export const FORM_SAVING = "FORM_SAVING"
export const FORM_ACTION_EVENT_EMITTED = 'FORM_ACTION_EVENT_EMITTED';
export const FORM_SAVE_SUCCEEDED = "FORM_SAVE_SUCCEEDED";
export const FORM_SAVE_FAILED = "FORM_SAVE_FAILED";


export const ACTION_SAVE_SUCCEEDED = "ACTION_SAVE_SUCCEEDED"
export const ACTION_SAVE_FAILED = "ACTION_SAVE_FAILED"
