
export const SCHEMA_LOAD_INITIATE = "SCHEMA_LOAD_INITIATE"
export const SCHEMA_LOAD_START = "SCHEMA_LOAD_START"
export const SCHEMA_LOAD_FINISHED = "SCHEMA_LOAD_FINISHED"
export const SCHEMA_LOAD_FAILED = "SCHEMA_LOAD_FAILED"